- hosts: awsbuntu
  become: yes
  tasks:
    - name: installing APACHE2
      apt: name=apache2 update_cache=yes
    - name: installing mysql
      apt: name=mysql-server update_cache=yes
    - name: installing PHP + modules
      apt: name=php update_cache=yes state=latest
    - name: APACHE2 restart
      service:
       name: apache2
       state: restarted
    - name: mysql restart
      service:
       name: mysql
       state: restarted
    - name: phpinfo created
      shell: /bin/echo -e "<?php \n phpinfo() \n ?>"| /bin/cat > /var/www/html/phpinfo.php
