---
# tasks file for anemone, installing apache
- name: anemone is installing apache2
  apt: name=apache2 update_cache=yes
  notify: 
    - apache restart nota

- name: index.html placing
  copy: src=index.html dest={{website_root}}

- name: phpinfo.php placing
  copy: src=info-php-file.php dest={{website_root}}

- name: create website root
  file:
   path: /var/www/{{ item }}/public_html
   state: directory
   mode: 0755
  with_items:
   - "{{apache_domain}}"
   - "{{apache_domain2}}"
- name: virtal hosts update with example1.tld
  template: src=apache_default.j2 dest=/etc/apache2/sites-available/{{ item }}.conf owner=ubuntu group=ubuntu
  with_items:
   - "{{apache_domain}}"
   - "{{apache_domain2}}"

