---
# tasks file for anemone, installing apache
- name: anemone is installing apache2
  apt: name=apache2 update_cache=yes
  notify: 
    - apache restart nota

- name: index.html placing
  copy: src=index.html dest={{website_root}}

- name: phpinfo.php placing
  copy: src=info-php-file.php dest={{website_root}}

- name: create website root
  file:
   path: "{{ item.docroot }}"
   state: directory
   mode: 0755
  with_items: "{{host_virtuales}}"

- name: virtal hosts update with example websites
  template: src=apache_default.j2 dest=/etc/apache2/sites-available/{{ item.domain }}.conf owner=ubuntu group=ubuntu
  with_items: "{{host_virtuales}}"

